<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="1" /> <!-- Link 1 -->
  <xacro:property name="width2" value="0.05" />
  <xacro:property name="length2" value="0.05" /> 
  <xacro:property name="height2" value="0.05" /> <!-- Link 2 -->
  <xacro:property name="width3" value="0.056" />
  <xacro:property name="length3" value="0.056" /> 
  <xacro:property name="height3" value="0.051" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find lidar_description)/urdf/lidar.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find lidar_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="${width/2} ${-width/2} ${height1/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://lidar_description/meshes/estructura.dae"/>
      	<!-- <box size="${width} ${width} ${height1}"/> -->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${width/2} ${-width/2} ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="-0.0345 ${-width/2 - 0.0225} ${1.021}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width2} ${width2} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0345 ${width/2 + 0.0225} ${-1.021}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://lidar_description/meshes/Motor.dae"/>
	      <!-- <box size="${width2} ${width2} ${height2}"/> -->
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width2*width2 + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width2*width2)}" iyz="0.0"
	  izz="${mass / 12.0 * (width2*width2 + width2*width2)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${0.0415}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${length3} ${width3} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0345 ${width/2 + 0.0225} ${-1.0625}" rpy="0 0 0"/>
      <geometry>
      <mesh filename="package://lidar_description/meshes/Sensor.dae"/>
	      <!-- <box size="${width} ${width} ${height3}"/> -->
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width3*width3 + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width3*width3)}" iyz="0.0"
	  izz="${mass / 12.0 * (width3*width3 + width3*width3)}"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
